replicaCount: 1

node:
  volumeMounts:
    - name: ecdsa-key
      mountPath: /app/operator_keys/ecdsa_key.json
      subPath: ecdsa_key.json
      readOnly: true
    - name: arpa
      mountPath: /app/data/
    - name: config
      mountPath: /app/config/operator.yaml
      subPath: operator.yaml
    - name: config
      mountPath: /opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json
      subPath: default_linux_config.json
  env:
    - name: ARPA_NODE_ACCOUNT_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: YOUR_ECDSA_KEY_SECRET
          key: ecdsa-private-key-password
serviceAccount:
  create: false
  name: arpa

cloudwatch:
  enabled: true
  volumeMounts:
    - name: arpa
      mountPath: /app/data/
    - name: config
      mountPath: /opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json
      subPath: default_linux_config.json
  command:
    - /opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent
  args: []
volumes:
  - name: ecdsa-key
    secret:
      secretName: YOUR_ECDSA_KEY_SECRET
      items:
        - key: ecdsa-private-key
          path: ecdsa_key.json
  - name: arpa
    persistentVolumeClaim:
      claimName: arpa
configs:
  default_linux_config.json: |

    {
        "agent": {
                "run_as_user": "root",
                "region": "us-east-1",
                "mode": "onPremise"
        },
        "logs": {
            "logs_collected": {
                "files": {
                    "collect_list": [
                        {
                                "file_path": "/app/data/log/1/node.log",
                                "log_group_class": "STANDARD",
                                "log_group_name": "arpa-network-logs",
                                "log_stream_name": "YOUR_OPERATOR_ADDRES",
                                "retention_in_days": -1
                        },
                        {
                                "file_path": "/app/data/log/1/node_err.log",
                                "log_group_class": "STANDARD",
                                "log_group_name": "arpa-network-logs",
                                "log_stream_name": "YOUR_OPERATOR_ADDRES",
                                "retention_in_days": -1
                        }
                    ]
                }
            }
        }
    }

  operator.yaml: |

    node_committer_rpc_endpoint: "0.0.0.0:50061"
    node_advertised_committer_rpc_endpoint: "YOUR_EXTERNAL_ADDRESS:50061"
    node_management_rpc_endpoint: "0.0.0.0:50091"
    node_management_rpc_token: "c3VwZXJzZWNyZXR0b2tlbg==" # Change me
    node_statistics_http_endpoint: "0.0.0.0:50081"
    provider_endpoint: "wss://lb.drpc.org/ogws?network=ethereum" ## Your wss rpc endpoint
    chain_id: 1
    is_eigenlayer: true
    controller_address: "0xbd0620c34796a4d978aecad929a3ad3d6b86280b"
    adapter_address: "0xbd57b868bb3374faa88722d2ee7ba3023c744e05"
    controller_relayer_address: "0x2c73da7786311C8011480fB590B6AEF79f425D18"
    data_path: "/app/data/data1.sqlite"

    logger:
      context_logging: false
      log_file_path: /app/data/log/1/
      rolling_file_size: 10 gb

    account:
      keystore:
          password: env
          path: /app/operator_keys/ecdsa_key.json

    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: PreGrouping
        interval_millis: 0
        use_jitter: true
      - l_type: PostCommitGrouping
        interval_millis: 10000
        use_jitter: true
      - l_type: PostGrouping
        interval_millis: 10000
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 10000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false

    time_limits:
      block_time: 12
      dkg_timeout_duration: 40
      randomness_task_exclusive_window: 10
      listener_interval_millis: 10000
      dkg_wait_for_phase_interval_millis: 10000
      provider_polling_interval_millis: 10000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false

    relayed_chains:
      - chain_id: 10
        description: "OP"
        provider_endpoint: "wss://lb.drpc.org/ogws?network=optimism" ## Your wss rpc endpoint
        controller_oracle_address: "0xa6ca2cF29616f7b4c0EBc872b3a06a5e72A11E6D"
        adapter_address: "0xDEc250D24ECf7475De51C51371e4F73b204c5b84"
        listeners:
          - l_type: Block
            interval_millis: 0
            use_jitter: true
          - l_type: NewRandomnessTask
            interval_millis: 0
            use_jitter: true
          - l_type: ReadyToHandleRandomnessTask
            interval_millis: 1000
            use_jitter: true
          - l_type: RandomnessSignatureAggregation
            interval_millis: 2000
            use_jitter: false
        time_limits:
          block_time: 2
          randomness_task_exclusive_window: 10
          listener_interval_millis: 1000
          provider_polling_interval_millis: 1000
          provider_reset_descriptor:
            interval_millis: 5000
            max_attempts: 17280
            use_jitter: false
          contract_transaction_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 3
            use_jitter: true
          contract_view_retry_descriptor:
            base: 2
            factor: 500
            max_attempts: 5
            use_jitter: true
          commit_partial_signature_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 5
            use_jitter: false
      - chain_id: 8453
        description: "Base"
        provider_endpoint: "wss://lb.drpc.org/ogws?network=base" ## Your wss rpc endpoint
        controller_oracle_address: "0xf1CCf9Bfd94079Ced6FC151030896F2a295b5Fdf"
        adapter_address: "0xD1A1c06a23cD4F5755ae3e90b8dCc1608C40A58B"
        listeners:
          - l_type: Block
            interval_millis: 0
            use_jitter: true
          - l_type: NewRandomnessTask
            interval_millis: 0
            use_jitter: true
          - l_type: ReadyToHandleRandomnessTask
            interval_millis: 1000
            use_jitter: true
          - l_type: RandomnessSignatureAggregation
            interval_millis: 2000
            use_jitter: false
        time_limits:
          block_time: 2
          randomness_task_exclusive_window: 10
          listener_interval_millis: 1000
          provider_polling_interval_millis: 1000
          provider_reset_descriptor:
            interval_millis: 5000
            max_attempts: 17280
            use_jitter: false
          contract_transaction_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 3
            use_jitter: true
          contract_view_retry_descriptor:
            base: 2
            factor: 500
            max_attempts: 5
            use_jitter: true
          commit_partial_signature_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 5
            use_jitter: false
      - chain_id: 690
        description: "RedStone"
        provider_endpoint: "wss://rpc.redstonechain.com"
        controller_oracle_address: "0xBd57b868BB3374faA88722D2ee7bA3023C744e05"
        adapter_address: "0x88a10c3aCCC51B52F8C6c95D1c614aB6065C7163"
        listeners:
          - l_type: Block
            interval_millis: 0
            use_jitter: true
          - l_type: NewRandomnessTask
            interval_millis: 0
            use_jitter: true
          - l_type: ReadyToHandleRandomnessTask
            interval_millis: 1000
            use_jitter: true
          - l_type: RandomnessSignatureAggregation
            interval_millis: 2000
            use_jitter: false
        time_limits:
          block_time: 2
          randomness_task_exclusive_window: 10
          listener_interval_millis: 1000
          provider_polling_interval_millis: 1000
          provider_reset_descriptor:
            interval_millis: 5000
            max_attempts: 17280
            use_jitter: false
          contract_transaction_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 3
            use_jitter: true
          contract_view_retry_descriptor:
            base: 2
            factor: 500
            max_attempts: 5
            use_jitter: true
          commit_partial_signature_retry_descriptor:
            base: 2
            factor: 1000
            max_attempts: 5
            use_jitter: false
