apiVersion: v1
stringData:
  bls-private-key: |

    {
      "pubKey": "alskdfmlaksmdfklamsdlfmalsdfmlasdf",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "asfdkalskdmflkasmdlfkmasdlkf",
        "cipherparams": {
          "iv": "asldkfmaklsmdflmasldkf"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 12,
          "n": 213123,
          "p": 132,
          "r": 12,
          "salt": "asdlfmaslkdfmlaksmdflkamsdlfmasdf"
        },
        "mac": "alskfnmlasnflkasnlfdnasldnflasndlfnasldfnla"
      }
    }
  bls-private-key-hex: 'laksdnflkasldfnalknfpwjerpijqwpremawfmdsf'
  bls-private-key-password: 'lkansdlfknaskldnfklasndfknasdpfmapfsm'

  ecdsa-private-key: |

    {
      "address": "sadflkasmdflkamsldfas;df",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "as;dmflaskmdflasmdlfkmalsdf",
        "cipherparams": {
          "iv": "lakmdslfkmalsdmflkasdmfl"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 123,
          "n": 123123,
          "p": 12,
          "r": 823,
          "salt": "daslkfmklasdmfklmasdlkfmlakdsf"
        },
        "mac": "alsdkmflkamsdlfkmasldfmlaksdmlf"
      },
      "id": "alsdfmlkasmdlfkmasldf",
      "version": 3
    }

  ecdsa-private-key-password: anlNASLdnfaljksdnLANSDlnalsdkjnASLKJDNlwnqlo21n3lkASLDndalsd
kind: Secret
metadata:
  name: YOUROPERATORADDRESS
type: Opaque
