node:
  volumeMounts:
    - name: ecdsa-key
      mountPath: /app/operator_keys/ecdsa_key.json
      subPath: ecdsa_key.json
      readOnly: true
    - name: signer-ecdsa-key
      mountPath: /app/operator_keys/signer_ecdsa_key.json
    - name: aethos
      mountPath: /app/data/
    - name: config
      mountPath: /app/config/operator.yaml
      subPath: operator.yaml
  env:
    - name: REGISTRATION_PRIVATE_KEY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: YOUR_ECDSA_KEY_SECRET
          key: ecdsa-private-key-password
    - name: REGISTRATION_PRIVATE_KEY_STORE_PATH
      value: "/app/operator_keys/ecdsa_key.json"
    - name: AETHOS_SIGNING_PRIVATE_KEY_STORE_PATH
      value: "/app/operator_keys/signer_ecdsa_key.json"
    - name: AETHOS_SIGNING_ADDRESS
      valueFrom:
        secretKeyRef:
          name: YOUR_ECDSA_SIGN_KEY_SECRET
          key: ecdsa-public-key
    - name: OPERATOR_ID
      value: YOUR_OPERATOR_ADDRES ## Fill your operator ID
    - name: AETHOS_SIGNING_PRIVATE_KEY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: YOUR_ECDSA_KEY_SECRET
          key: ecdsa-private-key-password
    - name: PUBLIC_TASK_SERVER_ENDPOINT
      value: YOUR_EXTERNAL_ADDRESS:9010 ## Your External IP address for access to aethos node
    - name: ETH_RPC_URLS
      value: https://lb.drpc.org/ogrpc?network=ethereum, https://lb.drpc2.org/ogrpc?network=ethereum

serviceAccount:
  create: false
  name: aethos

volumes:
  - name: ecdsa-key
    secret:
      secretName: YOUR_ECDSA_KEY_SECRET
      items:
        - key: ecdsa-private-key
          path: ecdsa_key.json
  - name: signer-ecdsa-key
    secret:
      secretName: YOUR_ECDSA_SIGN_KEY_SECRET
      items:
        - key: ecdsa-private-key
          path: ecdsa_key.json
  - name: aethos
    persistentVolumeClaim:
      claimName: aethos
configs:
  ## Need double check after changes
  operator.yaml: |

    # this sets the logger level
    environment: production

    # avs service manager proxy address
    service_manager_contract: 0x07E26BF8060e33fA3771d88128b75493750515c1
    # avs directory address (eigenlayer ethereum mainnet)
    eigen_avs_directory_contract: 0x135DDa560e946695d6f155dACaFC6f1F25C1F5AF


    # avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
    eigen_avs_node_api_server_endpoint: 0.0.0.0:8080
    metrics_server_endpoint: 0.0.0.0:9090

    # grpc server for communication in between operator and aggregator
    internal_task_server_endpoint: 0.0.0.0:9010

    # grpc server on which the operator receives tasks

    # address which the aggregator listens on for operator signed messages
    middleware_server_endpoint: task.aethos.network:50051

    # db path
    db_path: /app/data/

    # enable log colors
    enable_log_color: true
